export const browserCoreExamples = [
  "penguins browser status",
  "penguins browser start",
  "penguins browser stop",
  "penguins browser tabs",
  "penguins browser open https://example.com",
  "penguins browser focus abcd1234",
  "penguins browser close abcd1234",
  "penguins browser screenshot",
  "penguins browser screenshot --full-page",
  "penguins browser screenshot --ref 12",
  "penguins browser snapshot",
  "penguins browser snapshot --format aria --limit 200",
  "penguins browser snapshot --efficient",
  "penguins browser snapshot --labels",
];

export const browserActionExamples = [
  "penguins browser navigate https://example.com",
  "penguins browser resize 1280 720",
  "penguins browser click 12 --double",
  'penguins browser type 23 "hello" --submit',
  "penguins browser press Enter",
  "penguins browser hover 44",
  "penguins browser drag 10 11",
  "penguins browser select 9 OptionA OptionB",
  "penguins browser upload /tmp/penguins/uploads/file.pdf",
  'penguins browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "penguins browser dialog --accept",
  'penguins browser wait --text "Done"',
  "penguins browser evaluate --fn '(el) => el.textContent' --ref 7",
  "penguins browser console --level error",
  "penguins browser pdf",
];
