#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${PENGUINS_INSTALL_E2E_IMAGE:-${PENGUINS_INSTALL_E2E_IMAGE:-penguins-install-e2e:local}}"
INSTALL_URL="${PENGUINS_INSTALL_URL:-${PENGUINS_INSTALL_URL:-https://penguins.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
PENGUINS_E2E_MODELS="${PENGUINS_E2E_MODELS:-${PENGUINS_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e PENGUINS_INSTALL_URL="$INSTALL_URL" \
  -e PENGUINS_INSTALL_TAG="${PENGUINS_INSTALL_TAG:-${PENGUINS_INSTALL_TAG:-latest}}" \
  -e PENGUINS_E2E_MODELS="$PENGUINS_E2E_MODELS" \
  -e PENGUINS_INSTALL_E2E_PREVIOUS="${PENGUINS_INSTALL_E2E_PREVIOUS:-${PENGUINS_INSTALL_E2E_PREVIOUS:-}}" \
  -e PENGUINS_INSTALL_E2E_SKIP_PREVIOUS="${PENGUINS_INSTALL_E2E_SKIP_PREVIOUS:-${PENGUINS_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
